c_compiler:                    # [win]
  - vs2022                     # [win]
cxx_compiler:                  # [win]
  - vs2022                     # [win]
c_stdlib_version:              # [linux]
  - "2.17"                     # [linux]
