{% set name = "treelite" %}
{% set version = "0.93" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dmlc/treelite/archive/{{ version }}.tar.gz
  sha256: 7d347372f7fdc069904afe93e69ed0bf696ba42d271fe2f8bf6835d2ab2f45d5
  patches:
    - 0001-use-dynamic-libprotobuf.patch
    - 0002-disable-static-libs.patch
    - 0003-py38-windows-dll-path-fix.patch

build:
  number: 0

requirements:
  build:
    - cmake >=3.14
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - pip >=19.0
    - libprotobuf
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - treelite
    - treelite_runtime

about:
  home: https://github.com/dmlc/treelite
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Model compiler for decision tree ensembles'

  description: 'Treelite is a model compiler for efficient deployment of decision tree ensembles.'
  doc_url: https://treelite.readthedocs.io/
  dev_url: https://github.com/dmlc/treelite

extra:
  recipe-maintainers:
    - hcho3
