{% set name = "treelite" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dmlc/treelite/archive/{{ version }}.tar.gz
  sha256: e8aedbb9ee02d9cbf71ce2c0e55338e7433e2e360d1bca1e9bdab60498cd9a06

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake >=3.14
    - ninja
    - fmt
    - rapidjson
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip >=19.0
  run:
    - python
    - numpy
    - scipy
    - setuptools

test:
  requires:
    - setuptools
  imports:
    - treelite
    - treelite_runtime

about:
  home: https://github.com/dmlc/treelite
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Model compiler for decision tree ensembles

  description: Treelite is a model compiler for efficient deployment of decision tree ensembles.
  doc_url: https://treelite.readthedocs.io/
  dev_url: https://github.com/dmlc/treelite

extra:
  recipe-maintainers:
    - hcho3
