{% set name = "treelite" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dmlc/treelite/archive/{{ version }}.tar.gz
  sha256: 0ec73263a7a2903f2b7663eef8e0bcae7f58cd01ebd1a16b6e7bf162f6ff98d0
  patches:
    - 0001-Open-libtreelite.so-with-global-visibility.patch

build:
  number: 0
  skip: true  # [python_impl == 'pypy' and win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake >=3.14
    - ninja
    - fmt
    - rapidjson >=v1.1.0.post20240409
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip >=19.0
    - hatchling >=1.12.1
  run:
    - python
    - numpy
    - scipy
    - packaging

test:
  requires:
    - setuptools
  imports:
    - treelite

about:
  home: https://github.com/dmlc/treelite
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Model compiler for decision tree ensembles

  description: Universal model exchange and serialization format for decision tree forests
  doc_url: https://treelite.readthedocs.io/
  dev_url: https://github.com/dmlc/treelite

extra:
  recipe-maintainers:
    - hcho3
